/**
 * LLM Verification Report Schema
 *
 * Defines the structure for verification test reports.
 * Reports are generated by running test prompts against the LLM
 * and analyzing the responses.
 */

// =============================================================================
// Core Types
// =============================================================================

export type TestStatus = "pass" | "fail" | "skip" | "error";
export type Severity = "critical" | "major" | "minor" | "info";

export interface TestCase {
  /** Unique identifier for the test case */
  id: string;

  /** Human-readable test name */
  name: string;

  /** Test description */
  description?: string;

  /** Input provided to the system */
  input: string;

  /** Expected output or behavior */
  expected: unknown;

  /** Actual output from the system */
  actual?: unknown;

  /** Test status */
  status: TestStatus;

  /** Detailed assertions that were checked */
  assertions: Assertion[];

  /** Duration in milliseconds */
  duration_ms?: number;

  /** Additional notes or observations */
  notes?: string;
}

export interface Assertion {
  /** What was being checked */
  name: string;

  /** Did it pass? */
  passed: boolean;

  /** Expected value */
  expected?: unknown;

  /** Actual value */
  actual?: unknown;

  /** Explanation if failed */
  message?: string;

  /** Severity if failed */
  severity?: Severity;
}

// =============================================================================
// Test Suite
// =============================================================================

export interface TestSuite {
  /** Suite identifier (e.g., "inbox-processing", "search-quality") */
  id: string;

  /** Human-readable suite name */
  name: string;

  /** Suite description */
  description?: string;

  /** Test cases in this suite */
  cases: TestCase[];

  /** Overall suite status */
  status: TestStatus;

  /** Suite-level metrics */
  metrics: SuiteMetrics;
}

export interface SuiteMetrics {
  /** Total number of test cases */
  total: number;

  /** Number of passed tests */
  passed: number;

  /** Number of failed tests */
  failed: number;

  /** Number of skipped tests */
  skipped: number;

  /** Number of errored tests */
  errored: number;

  /** Pass rate as percentage */
  pass_rate: number;

  /** Total duration in milliseconds */
  duration_ms: number;
}

// =============================================================================
// Verification Report
// =============================================================================

export interface VerificationReport {
  /** Report metadata */
  metadata: ReportMetadata;

  /** Summary of all results */
  summary: ReportSummary;

  /** Individual test suites */
  suites: TestSuite[];

  /** Critical issues that need attention */
  critical_issues: CriticalIssue[];

  /** Recommendations for improvement */
  recommendations: string[];
}

export interface ReportMetadata {
  /** When the report was generated */
  generated_at: string;

  /** Version of the application tested */
  app_version?: string;

  /** Git commit hash */
  git_commit?: string;

  /** Git branch */
  git_branch?: string;

  /** Environment (e.g., "development", "staging", "production") */
  environment: string;

  /** LLM model used for verification */
  llm_model: string;

  /** Who/what triggered the verification */
  triggered_by?: string;
}

export interface ReportSummary {
  /** Overall status */
  overall_status: TestStatus;

  /** Total tests across all suites */
  total_tests: number;

  /** Total passed */
  total_passed: number;

  /** Total failed */
  total_failed: number;

  /** Overall pass rate */
  pass_rate: number;

  /** Total duration */
  total_duration_ms: number;

  /** Suite-level breakdown */
  suite_breakdown: {
    suite_id: string;
    suite_name: string;
    status: TestStatus;
    pass_rate: number;
  }[];
}

export interface CriticalIssue {
  /** Issue severity */
  severity: "critical" | "major";

  /** Which suite/test this relates to */
  source: string;

  /** Issue description */
  description: string;

  /** Potential impact */
  impact: string;

  /** Suggested fix */
  suggested_fix?: string;
}

// =============================================================================
// Report Builder Helpers
// =============================================================================

export function createEmptyReport(
  metadata: Partial<ReportMetadata>
): VerificationReport {
  return {
    metadata: {
      generated_at: new Date().toISOString(),
      environment: "development",
      llm_model: "unknown",
      ...metadata,
    },
    summary: {
      overall_status: "pass",
      total_tests: 0,
      total_passed: 0,
      total_failed: 0,
      pass_rate: 100,
      total_duration_ms: 0,
      suite_breakdown: [],
    },
    suites: [],
    critical_issues: [],
    recommendations: [],
  };
}

export function calculateSuiteMetrics(cases: TestCase[]): SuiteMetrics {
  const total = cases.length;
  const passed = cases.filter((c) => c.status === "pass").length;
  const failed = cases.filter((c) => c.status === "fail").length;
  const skipped = cases.filter((c) => c.status === "skip").length;
  const errored = cases.filter((c) => c.status === "error").length;
  const duration_ms = cases.reduce((sum, c) => sum + (c.duration_ms || 0), 0);

  return {
    total,
    passed,
    failed,
    skipped,
    errored,
    pass_rate: total > 0 ? (passed / total) * 100 : 100,
    duration_ms,
  };
}

export function calculateSuiteStatus(metrics: SuiteMetrics): TestStatus {
  if (metrics.errored > 0) return "error";
  if (metrics.failed > 0) return "fail";
  if (metrics.skipped === metrics.total) return "skip";
  return "pass";
}

export function finalizeSuite(suite: Omit<TestSuite, "status" | "metrics">): TestSuite {
  const metrics = calculateSuiteMetrics(suite.cases);
  const status = calculateSuiteStatus(metrics);
  return { ...suite, metrics, status };
}

export function finalizeReport(report: VerificationReport): VerificationReport {
  // Calculate summary from suites
  const allCases = report.suites.flatMap((s) => s.cases);
  const totalMetrics = calculateSuiteMetrics(allCases);

  report.summary = {
    overall_status: calculateSuiteStatus(totalMetrics),
    total_tests: totalMetrics.total,
    total_passed: totalMetrics.passed,
    total_failed: totalMetrics.failed,
    pass_rate: totalMetrics.pass_rate,
    total_duration_ms: totalMetrics.duration_ms,
    suite_breakdown: report.suites.map((s) => ({
      suite_id: s.id,
      suite_name: s.name,
      status: s.status,
      pass_rate: s.metrics.pass_rate,
    })),
  };

  // Collect critical issues from failed tests
  for (const suite of report.suites) {
    for (const testCase of suite.cases) {
      if (testCase.status === "fail") {
        const criticalAssertions = testCase.assertions.filter(
          (a) => !a.passed && (a.severity === "critical" || a.severity === "major")
        );
        for (const assertion of criticalAssertions) {
          report.critical_issues.push({
            severity: assertion.severity as "critical" | "major",
            source: `${suite.name} > ${testCase.name}`,
            description: assertion.message || assertion.name,
            impact: `${assertion.name} assertion failed`,
          });
        }
      }
    }
  }

  return report;
}
